# Config file for automatic testing at travis-ci.org

language: python
dist: xenial

install:
  - pip install -U tox

cache:
  directories:
    - .dev/.tox
before_cache:
  - rm -rf .dev/.tox/log
  - rm -rf .dev/.tox/dist
  # --
  - rm -rf .dev/.tox/py37/log
  - rm -rf .dev/.tox/py36/log
  - rm -rf .dev/.tox/mypy/log
  - rm -rf .dev/.tox/flake8/log
  # --
  - rm -rf .dev/.tox/py37/lib/python3.7/site-packages/{{ cookiecutter.project_slug }}*
  - rm -rf .dev/.tox/py36/lib/python3.6/site-packages/{{ cookiecutter.project_slug }}*
  - rm -rf .dev/.tox/mypy/lib/python3.7/site-packages/{{ cookiecutter.project_slug }}*
  - rm -rf .dev/.tox/flake8/lib/python3.7/site-packages/{{ cookiecutter.project_slug }}*
  # --
  - mv .dev/.tox/py37/coverage.xml .dev/coverage-py37.xml
  - mv .dev/.tox/py36/coverage.xml .dev/coverage-py36.xml

stages:
  - name: test
{%- if cookiecutter.use_pypi_deployment_with_travis == 'y' %}
  - name: deploy
    if: tag IS present
{%- endif %}

jobs:
  include:
    # --
    - stage: test
      name: "tests python3.7"
      python: 3.7
      script: tox -e py37
      after_success:
        - pip install codecov
        - codecov --file .dev/coverage-py37.xml
    - name: "tests python3.6"
      python: 3.6
      script: tox -e py36
    - name: "mypy"
      python: 3.7
      script: tox -e mypy
    - name: "flake8"
      python: 3.7
      script: tox -e flake8
{%- if cookiecutter.use_pypi_deployment_with_travis == 'y' %}
    # --
    - stage: deploy
      python: 3.7
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: {{ cookiecutter.pypi_username }}
        password:
          secure: PLEASE_REPLACE_ME
        on:
          tags: true
          repo: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
          python: 3.7
{%- endif %}
